MeyawoPortfolio/Controllers/TestimonialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MeyawoPortfolio.Models;

namespace MeyawoPortfolio.Controllers
{
    public class TestimonialController : Controller
    {
        DbMyPortfolioEntities db = new DbMyPortfolioEntities();
        public ActionResult Index()
        {
            var values = db.Tbl_Testimonial.ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult AddTestimonial()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddTestimonial(Tbl_Testimonial testimonial)
        {
            db.Tbl_Testimonial.Add(testimonial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteTestimonial(int id)
        {
            var testimonial = db.Tbl_Testimonial.Find(id);
            db.Tbl_Testimonial.Remove(testimonial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateTestimonial(int id)
        {
            var testimonial = db.Tbl_Testimonial.Find(id);
            return View(testimonial);
        }
        [HttpPost]
        public ActionResult UpdateTestimonial(Tbl_Testimonial p)
        {
            var testimonial = db.Tbl_Testimonial.Find(p.TestimonialID);
            testimonial.NameSurname = p.NameSurname;
            testimonial.Description = p.Description;
            testimonial.Image = p.Image;
            testimonial.Status = p.Status;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MeyawoPortfolio/Views/Testimonial/AddTestimonial.cshtml
@model MeyawoPortfolio.Models.Tbl_Testimonial

@{
    ViewBag.Title = "AddTestimonial";
    Layout = "~/Views/AdminLayout/_Layout.cshtml";
}

<h4>Referans Ekleme Sayfası</h4>
<br />
@using (Html.BeginForm("AddTestimonial", "Testimonial", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Adı Soyadı")
    @Html.TextBoxFor(x => x.NameSurname, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Görsel")
    @Html.TextBoxFor(x => x.Image, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Durum")
    @Html.TextBoxFor(x => x.Status, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.Description, 5, 7, new { @class = "table table-bordered" })
    <br />
    <button class="btn btn-outline-primary col-md-12">Referans Ekle</button>
</div>
}

MeyawoPortfolio/Views/Testimonial/Index.cshtml
@model List<MeyawoPortfolio.Models.Tbl_Testimonial>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminLayout/_Layout.cshtml";
}

<h2>Referanslarım</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Adı Soyadı</th>
        <th>Açıklama</th>
        <th>Durum</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.TestimonialID</td>
            <td>@item.NameSurname</td>
            <td>@item.Description</td>
            <td>@item.Status</td>
            <td> <a href="/Testimonial/UpdateTestimonial/@item.TestimonialID" class="btn btn-outline-success">Güncelle</a></td>
            <td> <a href="/Testimonial/DeleteTestimonial/@item.TestimonialID" class="btn btn-outline-danger">Sil</a></td>
        </tr>
    }
</table>
<a href="/Testimonial/AddTestimonial" class="btn btn-outline-primary col-12">Yeni Referans Ekle!</a>

MeyawoPortfolio/Views/Testimonial/UpdateTestimonial.cshtml
@model MeyawoPortfolio.Models.Tbl_Testimonial

@{
    ViewBag.Title = "UpdateTestimonial";
    Layout = "~/Views/AdminLayout/_Layout.cshtml";
}

<h4>Referans Güncelleme Sayfası</h4>
<br />
@using (Html.BeginForm("UpdateTestimonial", "Testimonial", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.TestimonialID, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Adı Soyadı")
    @Html.TextBoxFor(x => x.NameSurname, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.Description, 5, 7, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Görsel")
    @Html.TextBoxFor(x => x.Image, new { @class = "table table-bordered" })
    <br />
    @Html.Label("Durum")
    @Html.TextBoxFor(x => x.Status, new { @class = "table table-bordered" })
    <br />
    <button class="btn btn-outline-primary col-md-12">Güncelle</button>
</div>
}